## Importacao das bibliotecas

In [1]:
import numpy as np

## Trabalhando os metodos

In [2]:
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2, 3.5, 5.1])

In [6]:
b.dtype

dtype('float64')

In [7]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [8]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [9]:
c.dtype

dtype('complex128')

In [13]:
np.zeros( (3, 4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [14]:
np.empty( (2,3) ) 

array([[1.6069236e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [15]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [16]:
np.arange( 0, 2, 0.3 ) 

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [17]:
from numpy import pi

In [18]:
np.linspace( 0, 2, 9 )

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [19]:
x = np.linspace( 0, 2*pi, 100 )

In [20]:
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [21]:
f = np.sin(x)

In [22]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

### Imprimindo arrays

In [23]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [24]:
b = np.arange(12).reshape(4,3) 
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


### Operacoes basicas

In [30]:
a = np.array( [20,30,40,50] )

In [31]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [32]:
c = a - b
c

array([20, 29, 38, 47])

In [33]:
b**2

array([0, 1, 4, 9])

In [34]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [35]:
a<35

array([ True,  True, False, False])

In [36]:
A = np.array( [[1,1],
               [0,1]] )

In [37]:
B = np.array( [[2,0],
               [3,4]] )

In [38]:
A * B 

array([[2, 0],
       [0, 4]])

In [39]:
A @ B

array([[5, 4],
       [3, 4]])

In [40]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [41]:
rg = np.random.default_rng(1)

In [46]:
a = np.ones((2,3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
b = rg.random((2,3))
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [50]:
a *= 3
a

array([[9, 9, 9],
       [9, 9, 9]])

In [48]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [52]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [56]:
b.sum(axis=1) 

array([ 6, 22, 38])

In [58]:
b.min(axis=1) 

array([0, 4, 8])

In [59]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Funcoes universais

In [60]:
B = np.arange(3)
B

array([0, 1, 2])

In [61]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [62]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [63]:
C = np.array([2., -1., 4.])

In [64]:
np.add(B, C)

array([2., 0., 6.])